networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24

services:
  # デモUIサービス
  demo_ui:
    build: .
    working_dir: /app/demo/ui
    command: uv run main.py
    ports:
      - "12000:12000"
    volumes:
      - ./.env:/app/demo/ui/.env
    networks:
      my_network:
        ipv4_address: 192.168.100.2

  # CrewAIエージェントサービス
  crewai_agent:
    build: .
    working_dir: /app/samples/python/agents/crewai
    command: uv run . --host 192.168.100.3 --port 8080
    # ports:
    #   - "8080:8080"
    volumes:
      - ./.env:/app/samples/python/agents/crewai/.env
    networks:
      my_network:
        ipv4_address: 192.168.100.3

  # Google ADKエージェントサービス
  google_adk_agent:
    build: .
    working_dir: /app/samples/python/agents/google_adk
    command: uv run . --host 192.168.100.4 --port 8080
    # ports:
    #   - "8080:8080"
    volumes:
      - ./.env:/app/samples/python/agents/google_adk/.env
    networks:
      my_network:
        ipv4_address: 192.168.100.4

  # Langgraphエージェントサービス
  langgraph_agent:
    build: .
    working_dir: /app/samples/python/agents/langgraph
    command: uv run . --host 192.168.100.5 --port 8080
    # ports:
    #   - "8080:8080"
    volumes:
      - ./.env:/app/samples/python/agents/langgraph/.env
    networks:
      my_network:
        ipv4_address: 192.168.100.5
